"""add_missing_columns

Revision ID: c15618131a22
Revises: 
Create Date: 2026-06-16 17:42:50.779161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c15618131a22'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_analyses_is_deleted'), 'analyses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_analyses_pull_request_id'), 'analyses', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_analyses_repository_id'), 'analyses', ['repository_id'], unique=False)
    op.add_column('code_smells', sa.Column('start_line', sa.Integer(), nullable=True))
    op.add_column('code_smells', sa.Column('end_line', sa.Integer(), nullable=True))
    op.add_column('code_smells', sa.Column('code_snippet', sa.Text(), nullable=True))
    op.add_column('code_smells', sa.Column('issue_explanation', sa.Text(), nullable=True))
    op.create_index(op.f('ix_code_smells_analysis_id'), 'code_smells', ['analysis_id'], unique=False)
    op.add_column('generated_fixes', sa.Column('build_status', sa.String(), nullable=True))
    op.add_column('generated_fixes', sa.Column('build_errors', sa.Text(), nullable=True))
    op.add_column('generated_fixes', sa.Column('tests_status', sa.String(), nullable=True))
    op.add_column('generated_fixes', sa.Column('tests_errors', sa.Text(), nullable=True))
    op.add_column('generated_fixes', sa.Column('verification_score', sa.Integer(), nullable=True))
    op.add_column('generated_fixes', sa.Column('resolved', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_health_scores_analysis_id'), 'health_scores', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_pull_requests_repository_id'), 'pull_requests', ['repository_id'], unique=False)
    op.create_index(op.f('ix_reports_analysis_id'), 'reports', ['analysis_id'], unique=False)
    op.add_column('repositories', sa.Column('is_connected', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_repositories_user_id'), 'repositories', ['user_id'], unique=False)
    op.add_column('security_findings', sa.Column('start_line', sa.Integer(), nullable=True))
    op.add_column('security_findings', sa.Column('end_line', sa.Integer(), nullable=True))
    op.add_column('security_findings', sa.Column('code_snippet', sa.Text(), nullable=True))
    op.add_column('security_findings', sa.Column('issue_explanation', sa.Text(), nullable=True))
    op.create_index(op.f('ix_security_findings_analysis_id'), 'security_findings', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_test_suggestions_analysis_id'), 'test_suggestions', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_suggestions_analysis_id'), table_name='test_suggestions')
    op.drop_index(op.f('ix_security_findings_analysis_id'), table_name='security_findings')
    op.drop_column('security_findings', 'issue_explanation')
    op.drop_column('security_findings', 'code_snippet')
    op.drop_column('security_findings', 'end_line')
    op.drop_column('security_findings', 'start_line')
    op.drop_index(op.f('ix_repositories_user_id'), table_name='repositories')
    op.drop_column('repositories', 'is_connected')
    op.drop_index(op.f('ix_reports_analysis_id'), table_name='reports')
    op.drop_index(op.f('ix_pull_requests_repository_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_health_scores_analysis_id'), table_name='health_scores')
    op.drop_column('generated_fixes', 'resolved')
    op.drop_column('generated_fixes', 'verification_score')
    op.drop_column('generated_fixes', 'tests_errors')
    op.drop_column('generated_fixes', 'tests_status')
    op.drop_column('generated_fixes', 'build_errors')
    op.drop_column('generated_fixes', 'build_status')
    op.drop_index(op.f('ix_code_smells_analysis_id'), table_name='code_smells')
    op.drop_column('code_smells', 'issue_explanation')
    op.drop_column('code_smells', 'code_snippet')
    op.drop_column('code_smells', 'end_line')
    op.drop_column('code_smells', 'start_line')
    op.drop_index(op.f('ix_analyses_repository_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_pull_request_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_is_deleted'), table_name='analyses')
    op.drop_column('analyses', 'is_deleted')
    # ### end Alembic commands ###
