"""add_syntax_semantic_validation_columns

Revision ID: d0e6e4a97dc9
Revises: c15618131a22
Create Date: 2026-06-18 16:44:46.133710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e6e4a97dc9'
down_revision: Union[str, Sequence[str], None] = 'c15618131a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_fixes', sa.Column('syntax_status', sa.String(), nullable=True))
    op.add_column('generated_fixes', sa.Column('syntax_errors', sa.Text(), nullable=True))
    op.add_column('generated_fixes', sa.Column('semantic_status', sa.String(), nullable=True))
    op.add_column('generated_fixes', sa.Column('semantic_errors', sa.Text(), nullable=True))
    op.add_column('generated_fixes', sa.Column('lint_status', sa.String(), nullable=True))
    op.add_column('generated_fixes', sa.Column('lint_errors', sa.Text(), nullable=True))
    op.add_column('generated_fixes', sa.Column('diff_status', sa.String(), nullable=True))
    op.add_column('generated_fixes', sa.Column('diff_errors', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_fixes', 'diff_errors')
    op.drop_column('generated_fixes', 'diff_status')
    op.drop_column('generated_fixes', 'lint_errors')
    op.drop_column('generated_fixes', 'lint_status')
    op.drop_column('generated_fixes', 'semantic_errors')
    op.drop_column('generated_fixes', 'semantic_status')
    op.drop_column('generated_fixes', 'syntax_errors')
    op.drop_column('generated_fixes', 'syntax_status')
    # ### end Alembic commands ###
